import { primaryColor, primaryColorHover } from "./configuration"
import { DEFAULT_LOCALE, LOCALES } from "../utils/constants"

export default {
  name: "events",
  label: "Events",
  label_singular: "Event",
  description: "Events feature a lobby, livestream, chat, breakout rooms, etc.",
  folder: "content/events",
  path: "{{fields.slug}}/{{slug}}",
  media_folder: "",
  public_folder: "",
  create: true,
  i18n: true,
  preview_path: "/event/{{fields.slug}}",
  summary: "{{title}} - {{fields.eventInformation.startTime.datetime}}",
  sortable_fields: ["title", "eventInformation.startTime.datetime"],
  fields: [
    {
      name: "templateKey",
      default: "events",
      widget: "hidden",
      i18n: "duplicate",
    },
    {
      name: "slug",
      label: "Slug",
      hint: "Enter a unique url slug for your event, i.e. demo-event",
      i18n: "duplicate",
    },
    {
      name: "title",
      label: "Title",
      hint: "Enter a unique title for your event",
      i18n: true,
    },
    {
      name: "body",
      label: "Body",
      widget: "markdown",
      required: false,
      hint: "Content displayed in lobby",
      i18n: true,
    },
    {
      name: "eventInformation",
      label: "Event Information",
      widget: "object",
      i18n: true,
      fields: [
        {
          name: "videoUrl",
          label: "LiveStream URL",
          widget: "string",
          hint: "Enter a livestream embed URL from YouTube, Vimeo, Facebook, etc.",
          required: false,
          i18n: true,
        },
        {
          name: "presentationMode",
          label: "Presentation Mode",
          hint: "How should this video be presented? A timed video will begin automatically playing during your event start time. A standard video will allow guests to play the video anytime.",
          widget: "select",
          options: [
            { label: "Livestream", value: "livestream" },
            { label: "Timed", value: "timed" },
            { label: "Standard", value: "standard" },
          ],
          default: ["livestream"],
          required: false,
        },
        {
          name: "startTime",
          label: "Start Time",
          widget: "datetimezone",
          i18n: "duplicate",
        },
        {
          name: "endTime",
          label: "End Time",
          widget: "datetimezone",
          i18n: "duplicate",
          required: false,
        },
      ],
    },
    {
      name: "eventGraphics",
      label: "Event Graphics",
      widget: "object",
      i18n: true,
      fields: [
        {
          name: "favicon",
          label: "Favicon",
          widget: "image",
          allow_multiple: false,
          required: false,
          hint: "Event specific favicon",
          i18n: "duplicate",
        },
        {
          name: "headerLogo",
          label: "Header Logo",
          widget: "image",
          allow_multiple: false,
          required: false,
          hint: "Event specific header logo",
          i18n: "duplicate",
        },
        {
          name: "lobbyImage",
          label: "Lobby Graphic",
          widget: "image",
          allow_multiple: false,
          required: false,
          hint: "Event specific lobby image",
          i18n: "duplicate",
        },
      ],
    },
    {
      name: "eventBranding",
      label: "Event Branding",
      widget: "object",
      i18n: true,
      fields: [
        {
          name: "primaryColor",
          label: "Primary Color",
          default: primaryColor,
          widget: "color",
          hint: "Event specific primary color used in header, buttons, links, etc",
          i18n: "duplicate",
        },
        {
          name: "primaryColorHover",
          label: "Primary Hover Color",
          default: primaryColorHover,
          widget: "color",
          hint: "Event specific hover color used in header, buttons, links, etc",
          i18n: "duplicate",
        },
      ],
    },
    {
      name: "eventSchedule",
      label: "Event Schedule",
      widget: "list",
      i18n: true,
      summary: "{{fields.title}} - {{fields.startTime.datetime}}",
      fields: [
        {
          name: "startTime",
          label: "StartTime",
          widget: "datetimezone",
          default: "",
          i18n: "duplicate",
          required: false,
        },
        {
          name: "title",
          label: "Title",
          hint: "Title for your schedule item",
          widget: "string",
          i18n: true,
        },
        {
          name: "description",
          label: "Description",
          hint: "Desription for your schedule item",
          widget: "text",
          i18n: true,
        },
      ],
    },
    {
      name: "eventRooms",
      label: "Event Rooms",
      widget: "list",
      i18n: true,
      fields: [
        {
          name: "slug",
          label: "Slug",
          widget: "string",
          hint: "Enter a unique room slug in the format of `my-digital-meeting`",
          i18n: "duplicate",
        },
        {
          name: "title",
          label: "Title",
          widget: "string",
          i18n: true,
        },
        {
          name: "description",
          label: "Description",
          widget: "text",
          i18n: true,
        },
        {
          name: "roomLocale",
          label: "Room Locale",
          hint: "Select a language for this room",
          widget: "select",
          options: LOCALES,
          default: DEFAULT_LOCALE,
        },
        {
          name: "roomType",
          label: "Room Type",
          widget: "select",
          options: [
            { label: "Jitsi", value: "jitsi" },
            { label: "Zoom", value: "zoom" },
            { label: "Google Meet", value: "google " },
          ],
          default: ["jitsi"],
          i18n: true,
        },
        {
          name: "roomUrl",
          label: "Room Url",
          hint: "If using a room other than Jitsi, enter your meeting link.",
          required: false,
        },
        {
          name: "image",
          label: "Room Image",
          widget: "image",
          allow_multiple: false,
          required: false,
          i18n: "duplicate",
        },
      ],
    },
    {
      name: "eventQA",
      label: "Event Q&A Information",
      widget: "list",
      i18n: true,
      fields: [
        {
          name: "question",
          label: "Question",
          hint: "Common question",
          widget: "text",
          i18n: true,
        },
        {
          name: "answer",
          label: "Answer",
          hint: "Common answer",
          widget: "text",
          i18n: true,
        },
      ],
    },
    {
      name: "eventSettings",
      label: "Event Settings",
      widget: "object",
      i18n: true,
      fields: [
        {
          label: "Enable All Events",
          name: "allEvents",
          widget: "boolean",
          default: true,
          i18n: "duplicate",
        },
        {
          label: "Enable All Events Label",
          name: "allEventsLabel",
          widget: "string",
          default: "All Events",
          i18n: true,
        },
        {
          label: "Enable Main Stage",
          name: "mainStage",
          widget: "boolean",
          default: true,
          i18n: "duplicate",
        },
        {
          label: "Main Stage Label",
          name: "mainStageLabel",
          widget: "string",
          default: "Main Stage",
          i18n: true,
        },
        {
          label: "Main Stage Feature",
          name: "mainStageFeature",
          widget: "select",
          default: "chat",
          options: [
            { label: "Chat", value: "chat" },
            { label: "Schedule", value: "schedule" },
          ],
          multiple: false,
          hint: "Feature chat or schedule with main stage",
          i18n: "duplicate",
        },
        {
          label: "Enable Chat",
          name: "chat",
          widget: "boolean",
          default: true,
          i18n: "duplicate",
        },
        {
          label: "Chat Label",
          name: "chatLabel",
          widget: "string",
          default: "Chat",
          i18n: true,
        },
        {
          label: "Enable Schedule",
          name: "schedule",
          widget: "boolean",
          default: true,
          i18n: "duplicate",
        },
        {
          label: "Schedule Label",
          name: "scheduleLabel",
          widget: "string",
          default: "Schedule",
          i18n: true,
        },
        {
          label: "Enable Rooms",
          name: "rooms",
          widget: "boolean",
          default: true,
          i18n: "duplicate",
        },
        {
          label: "Rooms Label",
          name: "roomsLabel",
          widget: "string",
          default: "Rooms",
          i18n: true,
        },
        {
          label: "Enable Q&A",
          name: "qa",
          widget: "boolean",
          default: true,
          i18n: "duplicate",
        },
        {
          label: "Q&A Label",
          name: "qaLabel",
          widget: "string",
          default: "Q&A",
          i18n: true,
        },
        {
          label: "Enable Guest Map",
          name: "map",
          widget: "boolean",
          default: false,
          i18n: "duplicate",
        },
        {
          label: "Map Label",
          name: "mapLabel",
          widget: "string",
          default: "Attendees",
          i18n: true,
        },
      ],
    },
  ],
}
